# Generated by Django 5.2.10 on 2026-02-03 16:29

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Programme Name')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='programmes/photos/', verbose_name='Programme Photo')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this programme should be treated as active.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
