# Generated by Django 5.2.10 on 2026-02-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ZHOD', 'ZHoCD'), ('CHAIR', 'Board Chairperson'), ('BOARD', 'Board Member'), ('ED', 'Executive Director'), ('PM', 'Program Manager'), ('FAM', 'Finance & Admin Manager')], max_length=10)),
                ('photo', models.ImageField(upload_to='leadership/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear higher up.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
