# Generated by Django 5.2.10 on 2026-06-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websiteapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(blank=True, upload_to="resources/")),
                ("external_url", models.URLField(blank=True, max_length=500)),
                ("published_date", models.DateField()),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
        migrations.AddField(
            model_name="leader",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
    ]
