# Generated by Django 5.2.10 on 2026-02-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Member Name (Organization/Hospital)')),
                ('address', models.TextField(help_text='The official physical address of the member.', verbose_name='Physical Address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Phone Number')),
                ('bed_band', models.CharField(choices=[('0-50', '0 - 50 Beds'), ('51-100', '51 - 100 Beds'), ('101+', '101+ Beds')], default='0-50', max_length=10, verbose_name='Number of Beds Band')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this member is currently active (subscriptions paid).', verbose_name='Is Active (Subscription Paid)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
