# Generated by Django 5.2.10 on 2026-02-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='website',
            field=models.URLField(blank=True, help_text='The official website URL (e.g., https://www.hospital.com)', null=True, verbose_name='Website Address'),
        ),
    ]
