# Generated by Django 5.2.10 on 2026-06-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=500)),
                ("published_date", models.DateField()),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
    ]
